name: Deploy to Surge 

on:
    push:
        branches: ['main']
    pull_request: 
        branches: ['main']

jobs: 
    runMultipleCommands: 
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install Node.js
              uses: actions/setup-node@v1
              with: 
                node-version: '14.x'  
        #Install dependencies    
            - name: Install dependencies
              run: npm install 

        #Build projects 
            - name: Deploy
              run: npm install --global surge && surge ./ --domain william-cecchetti-qa.surge.sh --token ${{ secrets.SURGE_TOKEN }}

